name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package + deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[singlecell,report,test]
      - name: Unit tests
        run: pytest -q
      - name: Smoke test (toy bulk)
        run: |
          make setup
          make toy-bulk
          make check OUT=out/toy-bulk
