name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package + deps
        working-directory: pathway-builder-starter
        run: |
          python -m pip install --upgrade pip
          pip install -e .[singlecell,report,test]
      - name: Run tests
        working-directory: pathway-builder-starter
        run: |
          pytest -q
